#!/usr/bin/env python3
"""Generate blog/drafts/manifest.json and HTML previews for the CRM's blog-approval tab.

Blog draft .md files are excluded from the Cloudflare deploy (**/*.md), so the
CRM UI can't read them directly. This script writes:

- manifest.json: a deployable snapshot of each draft's approval-relevant frontmatter
- preview/<slug>.html: each draft rendered with the real post template, so it can be
  read before approval. worker.js only serves /blog/drafts/preview/ to signed-in CRM
  users and marks it noindex.

Regenerated by the blog pipeline workflow and the Editor-in-Chief on every run.
"""
from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DRAFTS = ROOT / "blog" / "drafts"
PREVIEWS = DRAFTS / "preview"
TEMPLATE = ROOT / "blog" / "templates" / "post-template.html"
OUT = DRAFTS / "manifest.json"

FIELDS = ("title", "slug", "date", "review_status", "primary_keyword", "meta_description")

sys.path.insert(0, str(Path(__file__).resolve().parent))
from publish_validator import render_html, split_frontmatter  # noqa: E402


def _preview_html(template: str, data: dict, body: str) -> str:
    # render_html indexes these keys directly; drafts mid-pipeline may not have them all yet.
    filled = dict(data)
    for key in ("title", "meta_description", "canonical_url", "og_image", "date", "primary_keyword",
                "intro_hook", "feature_image", "feature_image_alt"):
        filled.setdefault(key, "")
        if filled[key] is None:
            filled[key] = ""
    for key in ("external_sources", "internal_links"):
        filled[key] = filled.get(key) or []
    html = render_html(template, filled, body)

    # The template's relative paths assume /blog/posts/<slug>; previews live one level deeper.
    html = re.sub(r'(["\'(])\.\./\.\./', r"\1/", html)
    html = re.sub(r'(["\'(])\.\./', r"\1/blog/", html)

    status = str(data.get("review_status") or "pending")
    html = html.replace("<head>", '<head>\n  <meta name="robots" content="noindex, nofollow">', 1)
    banner = (
        '<div style="position:sticky;top:0;z-index:9999;background:#c56a1d;color:#fff;'
        'font:600 14px/1.4 system-ui,sans-serif;padding:10px 16px;text-align:center">'
        f"Draft preview &middot; not published &middot; pipeline status: {status}"
        "</div>"
    )
    return re.sub(r"(<body[^>]*>)", r"\1" + banner, html, count=1)


def main() -> None:
    template = TEMPLATE.read_text(encoding="utf-8")
    PREVIEWS.mkdir(parents=True, exist_ok=True)
    for old in PREVIEWS.glob("*.html"):
        old.unlink()

    drafts = []
    for path in sorted(DRAFTS.glob("*.md")):
        if path.name.lower() == "readme.md":
            continue
        try:
            data, body = split_frontmatter(path.read_text(encoding="utf-8", errors="replace"))
        except Exception as exc:
            print(f"skipped {path.name}: {exc}")
            continue
        entry = {field: str(data.get(field) or "") for field in FIELDS}
        entry["slug"] = entry["slug"] or path.stem
        entry["review_status"] = entry["review_status"] or "pending"
        entry["file"] = path.name
        try:
            (PREVIEWS / f"{entry['slug']}.html").write_text(_preview_html(template, data, body), encoding="utf-8")
            entry["preview"] = f"/blog/drafts/preview/{entry['slug']}"
        except Exception as exc:
            print(f"no preview for {path.name}: {exc}")
        drafts.append(entry)

    OUT.write_text(
        json.dumps(
            {"generated_at": datetime.now(timezone.utc).isoformat(), "drafts": drafts},
            indent=1,
        ),
        encoding="utf-8",
    )
    print(f"manifest written: {OUT} ({len(drafts)} drafts, {sum('preview' in d for d in drafts)} previews)")


if __name__ == "__main__":
    main()
