#!/usr/bin/env python3
"""Generate blog/drafts/manifest.json for the CRM's blog-approval tab.

Blog draft .md files are excluded from the Cloudflare deploy (**/*.md), so the
CRM UI can't read them directly. This manifest is a deployable JSON snapshot
of each draft's approval-relevant frontmatter. Regenerated by the
Editor-in-Chief on every run (and whenever drafts change).
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DRAFTS = ROOT / "blog" / "drafts"
OUT = DRAFTS / "manifest.json"

FIELDS = ("title", "slug", "date", "review_status", "primary_keyword", "meta_description")


def parse_frontmatter(text: str) -> dict:
    """Minimal YAML frontmatter reader for simple key: value scalars."""
    meta: dict = {}
    if not text.startswith("---"):
        return meta
    body = text.split("---", 2)
    if len(body) < 3:
        return meta
    current_key = None
    for line in body[1].splitlines():
        if not line.strip():
            continue
        if line.startswith(("  ", "\t", "- ")):
            # continuation of a folded scalar or a list item — only extend strings
            if current_key and isinstance(meta.get(current_key), str) and not line.strip().startswith("- "):
                meta[current_key] += " " + line.strip()
            continue
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        current_key = key.strip()
        value = value.strip().strip("'\"")
        meta[current_key] = value
    return meta


def main() -> None:
    drafts = []
    for path in sorted(DRAFTS.glob("*.md")):
        if path.name.lower() == "readme.md":
            continue
        meta = parse_frontmatter(path.read_text(encoding="utf-8", errors="replace"))
        entry = {field: meta.get(field, "") for field in FIELDS}
        entry["slug"] = entry["slug"] or path.stem
        entry["review_status"] = entry["review_status"] or "pending"
        entry["file"] = path.name
        drafts.append(entry)

    OUT.write_text(
        json.dumps(
            {"generated_at": datetime.now(timezone.utc).isoformat(), "drafts": drafts},
            indent=1,
        ),
        encoding="utf-8",
    )
    print(f"manifest written: {OUT} ({len(drafts)} drafts)")


if __name__ == "__main__":
    main()
